// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/kritpi/agnos-swe-assignment/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// Adapter is an autogenerated mock type for the Adapter type
type Adapter struct {
	mock.Mock
}

type Adapter_Expecter struct {
	mock *mock.Mock
}

func (_m *Adapter) EXPECT() *Adapter_Expecter {
	return &Adapter_Expecter{mock: &_m.Mock}
}

// HospitalASearchPatient provides a mock function with given fields: ctx, id
func (_m *Adapter) HospitalASearchPatient(ctx context.Context, id string) (*domain.HospitalPatient, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for HospitalASearchPatient")
	}

	var r0 *domain.HospitalPatient
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.HospitalPatient, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.HospitalPatient); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.HospitalPatient)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Adapter_HospitalASearchPatient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HospitalASearchPatient'
type Adapter_HospitalASearchPatient_Call struct {
	*mock.Call
}

// HospitalASearchPatient is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *Adapter_Expecter) HospitalASearchPatient(ctx interface{}, id interface{}) *Adapter_HospitalASearchPatient_Call {
	return &Adapter_HospitalASearchPatient_Call{Call: _e.mock.On("HospitalASearchPatient", ctx, id)}
}

func (_c *Adapter_HospitalASearchPatient_Call) Run(run func(ctx context.Context, id string)) *Adapter_HospitalASearchPatient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Adapter_HospitalASearchPatient_Call) Return(_a0 *domain.HospitalPatient, _a1 error) *Adapter_HospitalASearchPatient_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Adapter_HospitalASearchPatient_Call) RunAndReturn(run func(context.Context, string) (*domain.HospitalPatient, error)) *Adapter_HospitalASearchPatient_Call {
	_c.Call.Return(run)
	return _c
}

// NewAdapter creates a new instance of Adapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *Adapter {
	mock := &Adapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
