// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// Transactional provides a mock function with given fields: ctx, f
func (_m *Repository) Transactional(ctx context.Context, f func(context.Context) error) error {
	ret := _m.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for Transactional")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = rf(ctx, f)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_Transactional_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Transactional'
type Repository_Transactional_Call struct {
	*mock.Call
}

// Transactional is a helper method to define mock.On call
//   - ctx context.Context
//   - f func(context.Context) error
func (_e *Repository_Expecter) Transactional(ctx interface{}, f interface{}) *Repository_Transactional_Call {
	return &Repository_Transactional_Call{Call: _e.mock.On("Transactional", ctx, f)}
}

func (_c *Repository_Transactional_Call) Run(run func(ctx context.Context, f func(context.Context) error)) *Repository_Transactional_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(context.Context) error))
	})
	return _c
}

func (_c *Repository_Transactional_Call) Return(_a0 error) *Repository_Transactional_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_Transactional_Call) RunAndReturn(run func(context.Context, func(context.Context) error) error) *Repository_Transactional_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
